# -*- coding: utf-8 -*-
"""ListaExercicio4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10yMpFz3-LpkbTjWcTzYLJsukvzZ5gTlZ

# 📊 Projeto Final – Análise Contábil com Ajuste Econômico

Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit.
"""

import pandas as pd

import streamlit as st


st.set_page_config(
    page_title = ("ListaExercicio4"),
)

st.header = ("Projeto Final - Análise Contábil com Ajuste Econômico")
st.write = ("Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit.")


df = pd.read_csv("/content/empresas_dados.csv", sep=';')
df.head(len(df))

"""3) Calcule os indicadores Margem Líquida e ROA e salve como novas coluna da df. Depois apresente os dois indicadores no mesmo gráfico de linhas, agrupado por Ano  (peso: 1,0)

- Margem Líquida = Lucro Líquido / Receita Líquida * 100
- ROA = Lucro Líquido / Ativo Total *  100
"""

df["Margem Líquida"] = (df["Lucro Líquido"] / df["Receita Líquida"]) * 100
df["ROA"] = (df["Lucro Líquido"] / df["Ativo Total"]) * 100

df_grouped = df.groupby("Ano")[["Margem Líquida", "ROA"]].mean().reset_index()

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))
plt.plot(df_grouped["Ano"], df_grouped["Margem Líquida"], label="Margem Líquida")
plt.plot(df_grouped["Ano"], df_grouped["ROA"], label="ROA")
plt.xlabel("Ano")
plt.ylabel("%")
plt.title("Margem Líquida e ROA por Ano (média das empresas)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""4) Utilize o pacote ipeadatapy e faça busca para encontrar o indicador que traga o IPCA, taxa de variação, em % e anual: (peso: 2,0)

- Baixe os dados no período de 2010 a 2024
- Altere o nome da coluna "YEAR" para "Ano"
- Altere o nome da coluna "VALUE ((% a.a.))" para "IPCA"
- Apresente a df para checar se tudo deu certo
"""


import ipeadatapy as ip

ip.list_series('IPCA')

ip.describe('PRECOS_IPCAG')

ip.timeseries('PRECOS_IPCAG', yearGreaterThan=2009, yearSmallerThan=2025)

ipca = ip.timeseries('PRECOS_IPCAG', yearGreaterThan=2009, yearSmallerThan=2025)

ipca = ipca.rename(columns={
    "YEAR": "Ano",
    "VALUE ((% a.a.))": "IPCA"
})

ipca

df

"""5) Combine as duas df (Excel e IPEA) em uma nova df e calcule nova coluna chamada Receita Real (peso: 2,0)

- Utilize a função `pd.merge()` para unificar as duas df utiilizando a coluna Ano como conexão (chave primária) entre elas
- Crie nova coluna chamada Receita Real que será o resultado da Receita Líquida de cada ano deduzido o IPCA do ano: `Receita Real = Receitta Líquida - ( Receita Líquida * (IPCA/100) )`
- Apresente a nova df combinada

"""

df = pd.read_csv("empresas_dados.csv", sep=";")
df_combinado = pd.merge(df, ipca, on="Ano")

df_combinado["Receita Real"] = df_combinado["Receita Líquida"] - (df_combinado["Receita Líquida"] * (df_combinado["IPCA"] / 100))
df_combinado[["Ano", "Empresa", "Receita Líquida", "IPCA", "Receita Real"]]

"""6) Crie gráfico de linha que apresente as variáveis Receita Líquida e Receita Real ao longo dos anos (no mesmo gráfico) (peso: 1,0)"""

grafico_df = df_combinado.groupby("Ano")[["Receita Líquida", "Receita Real"]].sum().reset_index()

plt.figure(figsize=(10, 5))
plt.plot(grafico_df["Ano"], grafico_df["Receita Líquida"], marker='o', label="Receita Líquida")
plt.plot(grafico_df["Ano"], grafico_df["Receita Real"], marker='s', label="Receita Real")
plt.xlabel("Ano")
plt.ylabel("Valor (R$)")
plt.title("Receita Líquida vs Receita Real por Ano")
plt.grid(True)
plt.legend()
st.pyplot(plt)

"""7) Faça os ajustes necessários e leve este projeto para a web usando GitHub e Streamlit (peso: 2,0)

- Caça os ajustes necessários no projeto para ser publicado no Streamlit
- Crie novo repositório público no GitHub e leve os arquivos .py e .csv pra lá. Aproveite e crie o arquivo requirements.txt com os pacotes utilizados no projeto
- Crie novo projeto no Streamlit e associe ao repositório da lista
"""
